# frozen_string_literal: true

source "https://rubygems.org"

# Just for fun on the test.rb
gem 'colorize', '~> 1.1'

# Dpends on psych which needs libyaml
gem 'rails', '~> 7.1', '>= 7.1.3.4'

# Needs libxml2 and libxslt
gem 'nokogiri', '~> 1.16', '>= 1.16.6'

