schema-version = "1.17.0"

description = '''
# LocalStack

Start LocalStack in the background:

```text
flox services start
flox activate --start-services
```

Once it starts, see available services with:

```text
localstack status services
```
'''

[include]
environments = [
  { dir = "../localstack" }
]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
