schema-version = "1.17.0"

description = '''
# Go development environment

Included tools:

```text
go        - compiler and tools
gopls     - language server
gotools   - standard tools (goimports, etc.)
go-task   - task runner
gore      - REPL
```

Try the sample app:

```text
go build && ./hello
```
'''

[include]
environments = [
  { dir = "../go" }
]

# Editor tooling and task runner for Go development.

[install]
go-task.pkg-path = "go-task"
go-task.pkg-group = "go-tools"
gopls.pkg-path = "gopls"
gopls.pkg-group = "go-tools"
gopls.priority = 4
gotools.pkg-path = "gotools"
gotools.pkg-group = "go-tools"
gomodifytags.pkg-path = "gomodifytags"
gomodifytags.pkg-group = "go-tools"
gotests.pkg-path = "gotests"
gotests.pkg-group = "go-tools"
gore.pkg-path = "gore"
gore.pkg-group = "go-tools"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
