version = 1


[install]
mac-app-util.flake = "github:hraban/mac-app-util"
jq.pkg-path = "jq"

# Example package to test
#raycast.pkg-path = "raycast"


[hook]
on-activate = '''
if [ -d $FLOX_ENV/Applications ]; then 
  FLOX_ENV_NAME=$(echo $_FLOX_ACTIVE_ENVIRONMENTS | jq '.[0].pointer.name')
  mac-app-util sync-trampolines \
    "$FLOX_ENV/Applications" \
    "$HOME/Applications/Flox ($FLOX_ENV_NAME) Apps"
fi
'''


[options]
systems = [
  "aarch64-darwin",
  "x86_64-darwin",
]
