schema-version = "1.10.0"

[include]
environments = [
  { dir = "../temporal" }
]

# gum is a demo-only tool for styled terminal output.

[install]
gum.pkg-path = "gum"
gum.pkg-group = "demo-tools"

[hook]
on-activate = '''
if [[ "${FLOX_ENVS_TESTING:-}" != "1" ]]; then
  gum style --border double --margin '1 2' \
    --padding '1 4' \
    'Start Temporal in the background:' \
    '  flox services start' \
    '  flox activate --start-services' '' \
    'Temporal gRPC endpoint:' \
    "  $TEMPORAL_HOST:$TEMPORAL_PORT" '' \
    'Temporal Web UI:' \
    "  http://$TEMPORAL_HOST:$TEMPORAL_UI_PORT" '' \
    'Temporal CLI:' \
    '  temporal operator namespace list' \
    '  temporal workflow list'
fi
'''
