schema-version = "1.10.0"

[include]
environments = [
  { dir = "../mariadb" }
]

# gum is a demo-only tool for styled terminal output.

[install]
gum.pkg-path = "gum"
gum.pkg-group = "demo-tools"

[hook]
on-activate = '''
if [[ "${FLOX_ENVS_TESTING:-}" != "1" ]]; then
  gum style --border double --margin '1 2' \
    --padding '1 4' \
    'Start MariaDB in the background:' \
    '  flox services start' \
    '  flox activate --start-services' '' \
    'Connect to MariaDB:' \
    "  mariadb --socket=$MARIADB_SOCKET -u $MARIADB_USER -p" '' \
    'Connection information:' \
    "  host=$MARIADB_HOST" \
    "  port=$MARIADB_PORT" \
    "  database=$MARIADB_DATABASE" \
    "  user=$MARIADB_USER"
fi
'''
