schema-version = "1.17.0"

description = '''
# MariaDB

Start MariaDB in the background:

```text
flox services start
flox activate --start-services
```
'''

[include]
environments = [
  { dir = "../mariadb" }
]

# gum is a demo-only tool for styled terminal output.

[install]
gum.pkg-path = "gum"
gum.pkg-group = "demo-tools"

[hook]
on-activate = '''
if [[ "${FLOX_ENVS_TESTING:-}" != "1" ]]; then
  gum style --border double --margin '1 2' \
    --padding '1 4' \
    'Connect to MariaDB:' \
    "  mariadb --socket=$MARIADB_SOCKET -u $MARIADB_USER -p" \
    '' \
    'Connection information:' \
    "  host=$MARIADB_HOST" \
    "  port=$MARIADB_PORT" \
    "  database=$MARIADB_DATABASE" \
    "  user=$MARIADB_USER"
fi
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
