schema-version = "1.17.0"

description = '''
# Node.js

Commands:

```text
npm install    Install packages
npm start      Run your app
node <file>    Run a script
```
'''

[include]
environments = [
  { dir = "../javascript-node" }
]

[install]
gum.pkg-path = "gum"
gum.pkg-group = "demo-tools"

[hook]
on-activate = '''
if [[ "${FLOX_ENVS_TESTING:-}" != "1" ]]; then
  gum style --border double --margin '1 2' \
    --padding '1 4' \
    'Node.js environment ready!' '' \
    'Node version:' \
    "  $(node --version)"
fi
'''

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
