schema-version = "1.10.0"

# Minimal MongoDB environment for use with [include].
#
# Include it in your own manifest:
#
#   [include]
#   environments = ["flox/mongodb"]
#
# Customize vars in your manifest to override defaults:
#
#   [vars]
#   MONGO_PORT = "27017"

[install]
mongodb-ce.pkg-path = "mongodb-ce"
mongodb-ce.pkg-group = "mongodb"

[vars]
MONGO_HOST = "127.0.0.1"
MONGO_PORT = "127017"

[hook]
on-activate = '''
export MONGO_DATA="$FLOX_ENV_CACHE/mongodb"

if [ ! -d "$MONGO_DATA" ]; then
  mkdir -m 0700 -p "$MONGO_DATA"
fi
'''

[services]
mongodb.command = '''
  MONGO_DATA="$FLOX_ENV_CACHE/mongodb"
  exec mongod --dbpath "$MONGO_DATA" \
    --bind_ip "$MONGO_HOST" --port "$MONGO_PORT"
'''
