#!/usr/bin/env bash
# lmstudio-info — display LM Studio + Agentic Tools configuration

echo "LM Studio + Agentic Tools Configuration"
echo ""
echo "Server:"
echo "  Host: ${LMS_HOST:-127.0.0.1}"
echo "  Port: ${LMS_PORT:-1234}"
echo "  API:  http://${LMS_HOST:-127.0.0.1}:${LMS_PORT:-1234}"
echo "  GUI:  ${LMS_GUI:-false}"
echo "  CORS: ${LMS_CORS_ORIGIN:-*}"
echo ""
if [ "${_FLOX_ENV_CUDA_DETECTION:-0}" = "1" ]; then
    echo "GPU: Available (CUDA detected, --gpu max default)"
else
    echo "GPU: Not detected (override: --gpu max|off)"
fi
echo "Context: ${LMS_CONTEXT_LENGTH:-131072} (override: --context-length or LMS_CONTEXT_LENGTH)"
echo ""
echo "Agentic Tools (auto-downloads and loads if needed):"
echo "  lms-launch claude --model <m>               Launch Claude Code"
echo "  lms-launch codex --model <m>                Launch Codex"
echo "  lms-launch opencode --model <m>             Launch OpenCode"
echo "  lms-launch claude --model <m> --context-length 65536  Custom context"
echo ""
echo "Model Management (advanced):"
echo "  lms get <model>                 Download a model manually"
echo "  lms load <model> --context-length 65536"
echo "                                  Load model manually"
echo "  lms ls                          List loaded models"
echo "  lms chat                        Interactive terminal chat"
echo ""
echo "Service Management:"
echo "  flox services status            Check service status"
echo "  flox services logs              View service logs"
echo "  lmstudio-health                 Test API endpoint"
echo ""
echo "Logs: ${LMS_LOG_DIR:-$HOME/.lmstudio/logs}/lm-studio.log"
echo ""
echo "Runtime Override Examples:"
echo "  LMS_HOST=0.0.0.0 flox activate -s"
echo "  LMS_PORT=8080 flox activate -s"
echo "  LMS_GUI=true flox activate"
