schema-version = "1.17.0"

description = '''
# LangChain with Ollama

Start Ollama in the background:

```text
flox services start
flox activate --start-services
```

Python packages available:

```text
langgraph, langchain-ollama, langchain-community
```

Check Ollama status:

```text
ollama list
```
'''

[include]
environments = [
  { dir = "../langchain" }
]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
