schema-version = "1.10.0"

[include]
environments = [
  { dir = "../redis" }
]

# gum is a demo-only tool for styled terminal output.

[install]
gum.pkg-path = "gum"
gum.pkg-group = "demo-tools"

[hook]
on-activate = '''
if [[ "${FLOX_ENVS_TESTING:-}" != "1" ]]; then
  gum style --border double --margin '1 2' \
    --padding '1 4' \
    'Start Redis in the background:' \
    '  flox services start' \
    '  flox activate --start-services' '' \
    'Connect to Redis:' \
    "  redis-cli -h $REDIS_HOST -p $REDIS_PORT" '' \
    'Connection information:' \
    "  host=$REDIS_HOST" \
    "  port=$REDIS_PORT"
fi
'''
