schema-version = "1.10.0"

# Minimal Go environment for use with [include].
#
# Include it in your own manifest:
#
#   [include]
#   environments = ["flox/go"]

[install]
go.pkg-path = "go"

[hook]
on-activate = '''
export GOENV="$FLOX_ENV_CACHE/go"
export GOMODCACHE="$FLOX_ENV_CACHE/go/pkg/mod"
'''
