name: "CI: finceptterminal"

on:
  push:
    branches: ["main"]
    paths:
      - "finceptterminal/**"
      - "finceptterminal-demo/**"
      - ".flox/pkgs/finceptterminal/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_finceptterminal.yml"
  pull_request:
    paths:
      - "finceptterminal/**"
      - "finceptterminal-demo/**"
      - ".flox/pkgs/finceptterminal/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_finceptterminal.yml"
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"
  attestations: "write"
  id-token: "write"

jobs:
  run:
    uses: "./.github/workflows/environment.yml"
    with:
      environment: "finceptterminal"
    secrets: inherit
