name: "CI: huggingface"

on:
  push:
    branches: ["main"]
    paths:
      - "huggingface/**"
      - "huggingface-demo/**"
      - ".flox/pkgs/huggingface-hub/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_huggingface.yml"
  pull_request:
    paths:
      - "huggingface/**"
      - "huggingface-demo/**"
      - ".flox/pkgs/huggingface-hub/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_huggingface.yml"
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"
  attestations: "write"
  id-token: "write"

jobs:
  run:
    uses: "./.github/workflows/environment.yml"
    with:
      environment: "huggingface"
    secrets: inherit
