name: "CI: hermes"

on:
  push:
    branches: ["main"]
    paths:
      - "hermes/**"
      - "hermes-demo/**"
      - ".flox/pkgs/hermes-agent/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_hermes.yml"
  pull_request:
    paths:
      - "hermes/**"
      - "hermes-demo/**"
      - ".flox/pkgs/hermes-agent/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
      - ".github/workflows/ci_hermes.yml"
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"
  attestations: "write"
  id-token: "write"

jobs:
  run:
    uses: "./.github/workflows/environment.yml"
    with:
      environment: "hermes"
    secrets: inherit
