name: "CI: redis"

on:
  push:
    branches: ["main"]
    paths:
      - "redis/**"
      - "redis-demo/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
  pull_request:
    paths:
      - "redis/**"
      - "redis-demo/**"
      - "flake.nix"
      - "flake.lock"
      - "scripts/**"
      - ".github/workflows/environment.yml"
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"
  attestations: "write"
  id-token: "write"

jobs:
  ci:
    uses: "./.github/workflows/environment.yml"
    with:
      environment: "redis"
    secrets: inherit
